# Generated by Django 4.2.13 on 2024-06-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Kontrahent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa_kontrahenta", models.CharField(max_length=255)),
                ("typ_kontrahenta", models.CharField(max_length=255)),
                ("ulica", models.CharField(max_length=255)),
                ("kod_pocztowy", models.CharField(max_length=10)),
                ("miasto", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ObszarDzialania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Powiat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RodzajUprawnien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RodzajZadania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Specjalista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=255)),
                ("nazwisko", models.CharField(max_length=255)),
                ("telefon", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "branza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.branza"
                    ),
                ),
                (
                    "obszar_dzialania",
                    models.ManyToManyField(
                        through="core.ObszarDzialania", to="core.powiat"
                    ),
                ),
                (
                    "rodzaj_uprawnien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rodzajuprawnien",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Typ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Wojewodztwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Zadanie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa_zadania", models.CharField(max_length=255)),
                ("data_wprowadzenia", models.DateField()),
                ("termin_statusu", models.DateField()),
                (
                    "wartosc_zadania",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "wycena",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("wykonawca", models.CharField(max_length=255)),
                (
                    "wycena_wykonawcy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "kontrahent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.kontrahent",
                    ),
                ),
                (
                    "przypisany_pracownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rodzaj_zadania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rodzajzadania",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.status"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecjalistaZadania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specjalista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.specjalista",
                    ),
                ),
                (
                    "zadanie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.zadanie"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="powiat",
            name="wojewodztwo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.wojewodztwo"
            ),
        ),
        migrations.AddField(
            model_name="obszardzialania",
            name="powiat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.powiat"
            ),
        ),
        migrations.AddField(
            model_name="obszardzialania",
            name="specjalista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.specjalista"
            ),
        ),
        migrations.AddField(
            model_name="kontrahent",
            name="powiat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.powiat"
            ),
        ),
    ]
