# Generated by Django 4.2.13 on 2024-07-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_branza_kontrahent_obszardzialania_powiat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zadanie",
            name="wycena_wykonawcy",
        ),
        migrations.RemoveField(
            model_name="zadanie",
            name="wykonawca",
        ),
        migrations.AddField(
            model_name="specjalistazadania",
            name="wycena_wykonawcy",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="specjalista",
            name="branza",
        ),
        migrations.CreateModel(
            name="SpecjalistaBranza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Branza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.branza"
                    ),
                ),
                (
                    "specjalista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.specjalista",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="specjalista",
            name="branza",
            field=models.ManyToManyField(
                through="core.SpecjalistaBranza", to="core.branza"
            ),
        ),
    ]
