# Generated by Django 4.2.14 on 2024-07-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_zadanie_wycena_wykonawcy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kontrahent",
            name="typ_kontrahenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.typ"
            ),
        ),
    ]
