# Generated by Django 4.2.14 on 2024-07-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_kontrahent_typ_kontrahenta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specjalista",
            name="rodzaj_uprawnien",
        ),
        migrations.AddField(
            model_name="specjalistabranza",
            name="rodzaj_uprawnien",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.rodzajuprawnien",
            ),
            preserve_default=False,
        ),
    ]
