# Generated by Django 4.2.15 on 2024-08-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_kontrahent_email_kontrahent_nr_budynku_lokalu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specjalista",
            name="branza",
        ),
        migrations.RemoveField(
            model_name="specjalista",
            name="obszar_dzialania",
        ),
        migrations.AlterField(
            model_name="specjalista",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="specjalista",
            name="telefon",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="zadanie",
            name="wartosc_zadania",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
