# Generated by Django 4.2.15 on 2024-08-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_specjalista_branza_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specjalistabranza",
            old_name="Branza",
            new_name="branza",
        ),
    ]
